### ISSUE TITLE
Add a CLI tool

### ISSUE THREAD

**Issue by soc221b** [soc221b/namanager#12]
We need a CLI tool which can be run instead of `python3 file_checker/main.py --settings settings.json`.

There is some examples of big project:
[nose](https://github.com/nose-devs/nose)

**Comment by arnavb** [comment]
For something similar to NCurses, we can use something from http://docs.python-guide.org/en/latest/scenarios/cli/

**Comment by soc221b** [comment]
I've done something according to nose, and I will read up your recommend tomorrow😴.
